server.port=8084
spring.application.name=notification-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=quizapplicationmanagement@gmail.com
spring.mail.password=xoftfijoyxhcqtbh

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.amqp.deserialization.trust.all=true
